added modal
oleksiihrushko/react-project pull request #1
Opened 2020-07-28 09:55 UTC by amie-affection

added components Modal and ModalPage

2020-07-28 10:14 UTC, oleksiihrushko commented on src/components/App.js
> +      <ModalPage/>
убераем

2020-07-28 10:15 UTC, oleksiihrushko requested changes

2020-07-28 10:15 UTC, oleksiihrushko commented on src/components/modal/Modal.js
> +const Modal = ({ closeModal }) => {
добавить параметры phrase и function(которая будет вызыватся по клику на "Да")

2020-07-28 18:35 UTC, oleksiihrushko requested changes
не вижу как в компонент приходит функция closeModal

2020-07-28 18:35 UTC, oleksiihrushko commented on src/components/modal/Modal.js
>        closeModal();
откуда теперь берется здесь closeModal?

2020-07-29 12:23 UTC, amie-affection commented on src/components/modal/Modal.js
>        closeModal();
deleted

2020-07-29 12:23 UTC, amie-affection commented on src/components/modal/Modal.js
> +const Modal = ({ closeModal }) => {
(text, onTrue)

2020-07-29 12:24 UTC, amie-affection commented on src/components/App.js
> +      <ModalPage/>
done

2020-07-29 15:46 UTC, oleksiihrushko requested changes

2020-07-29 15:46 UTC, oleksiihrushko commented on src/components/modal/Modal.js
> -      closeModal();
Алин, я думаю closeModal все таки нужен, но его надо бробрасывать в пропах, или я чет не так понял?

2020-07-30 12:44 UTC, amie-affection commented on src/components/modal/Modal.js
> -      closeModal();
fixed

2020-07-30 12:48 UTC, oleksiihrushko requested changes

2020-07-30 12:48 UTC, oleksiihrushko commented on src/components/App.js
> +}
Это было для проверки, уберай.

2020-07-30 12:48 UTC, oleksiihrushko commented on src/components/App.js
> +        <Modal text={"Вы действительно хотите выйти?"} onTrue={onTrue} />
Это было тоже для проверки, уберай

2020-07-30 14:09 UTC, merged